### ISSUE TITLE
Concurrency issue

### ISSUE THREAD

**Issue by cryptoquick** [jerry73204/par-stream#1]
Great library! It's very easy to use. However, I seem to get different behavior when I use this code:

https://github.com/FuzzrNet/Fuzzr/blob/0f4056889c9d737ebd3af0ea8e580116ebec39e0/src/data/thumbnails.rs#L58

vs. this code:

https://github.com/FuzzrNet/Fuzzr/blob/b7efe3086fef03b6061f99591dcf01405bfb8d31/src/data/thumbnails.rs#L100

I'm not sure why it's behaving the way it is, though. I'm also not sure how else to explain the issue.

If you want to check it out, just drag a folder full of images onto the window.

**Comment by jerry73204** [comment]
Here is my judgement from your code (not running your code yet, I'll check if I have time). Let's name the snipplets before and inside the async block "preparing" and "working" parts for ease of explanation.

```rust
.par_then_unordered(
    None,
    |args| {
        // preparing part
        async move {
            // working part
        }
    }
)
```

**Short answer**
ONLY the working part is distributed to workers, while the preparing isn't. The preparing part always run on single worker, and is called sequentially for each input item, causing the sequential behavior in your case.

**Long answer**
The preparing part is intended to capture and clone outer variables, so that the working part can process them. Heavy computation/IO routines should be placed inside the working part. It is useful when multiple stages share a common configuration.

```rust
let config: Arc<Config> = /* omit */;

stream.par_then_unordered(
    None,
    |args| {
        let config = config.clone();
        async move {
            let option1 = config.opton1;
            // ...loading file, etc
        }
    }
)
.par_then_unordered(
    None,
    |args| {
        let config = config.clone();
        async move {
            let option2 = config.opton2;
            // ...computation, etc
        }
    }
)
```

There are reasons to distribute the async part (or futures) but not the closure itself to parallel workers. By distributing the closure to parallel workers, the closure itself has to be cloneable. However, it's easy to have a non-cloneable variable in closure to break this property. Cloning the closure also causes lifetime issue if it captures outer variables.  So the closure is designed to run on single worker, and should only serves the initialization with minimal effort.

Besides, it seems your code has `ImageReader::open` in the async block that might blocks for a long time. I suggested [`par_map_unordered`](https://docs.rs/par-stream/0.2.1/par_stream/trait.ParStreamExt.html#method.par_map_unordered) instead of `par_then_unordered`. The blocking operation does not block the main thread, but still blocks the underlying async-std runtime. The `par_map_unordered` simply moves to a new thread that is out side of async-std runtime.

**Comment by cryptoquick** [comment]
That's very good advice. No need to take a closer look on my behalf, I think that's good enough direction so far. I just need to finish up a piece of the presentation layer and I'll get back to optimizing the image processing. Thank you so much!

**Comment by cryptoquick** [comment]
Okay, I'm back to it now.

I think you're right about par_map_unordered, but regardless of which I use, if I put the processing in the worker, it does it in parallel, but doesn't emit events until all is finished, and even then, it's only the last event.

I need events to be emitted right as they occur, in parallel, in a stream. How might I do this?

**Comment by cryptoquick** [comment]
This is my latest code if it helps

https://github.com/FuzzrNet/Fuzzr/blob/966ea5a71d76778d915511c48c0d6a0d4dd118ff/src/data/thumbnails.rs

**Comment by cryptoquick** [comment]
Yeah, it's super strange. I'm only getting a single value emitted from the stream if I put everything in the parallel worker.

**Comment by jerry73204** [comment]
I looked into your repo. It stuck in when an item is sent to a channel where distributed workers receives from. ([code](https://github.com/jerry73204/par-stream/blob/43d9290fc4fd9be2fb0c4e7e5309c60cfa66374b/src/stream.rs#L973)) The whole stream stopped working once the channel is full. Hence, increasing the internal channel size eliminates this issue. It seems that runtime stops to "poll" the channel with no reason, while other async tasks still work.

It's a weird issue. Maybe it needs some understanding of details of underlying impls to resolve this issue.

**Comment by cryptoquick** [comment]
Alright, I've modified your code just a little bit and inlined it into my function to better troubleshoot it. It seems to panic at like 161:
https://github.com/FuzzrNet/Fuzzr/blob/d992287e3866a19d69a06fcbb862433a566721b7/src/data/thumbnails.rs#L161

**Comment by jerry73204** [comment]
Good catch! Let me re-consider more rigorous error handling inside parallel stream.

**Comment by cryptoquick** [comment]
That'd be super helpful. Also, is there a method in par-stream that provides the stream after spawning the workers futures, like my modification?

**Comment by cryptoquick** [comment]
Hey, just wanted to let you know, I got my code to work. I'm using your `par_map_unordered` function, as you recommended. It works like a charm! And it is SO FAST! It's only marginally slower than my Rayon implementation, but user feedback is immediate, since it's streaming.

See it here:
https://github.com/FuzzrNet/Fuzzr/pull/92
